### PR TITLE
Another change in getGroupedRows

### PR DESCRIPTION
**Pull request by thoriphes**
renderData in get GroupedRows was ignoring potentially existent props.cellFactory.
We have added a check for it!

### CODE REVIEW

**Comment by stevelacy** [comment]
merged, thanks, publishing to 3.2.2

**Comment by thoriphes** [comment]
;-)

**Comment by stevelacy** [comment]
@thoriphes interested in sending a pr for #9?

**Comment by thoriphes** [comment]
Hmmm... I think I solved that by pure css :P

But will take a look tomorrow and let you know

**Pull request merged**
